import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import { Container,  Box, Typography } from '@mui/material';
import CustomizedTimeline from "@/components/CustomTimeline";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Container maxWith="sm">
            <Box sx={{ my: 4 }}>
              <Typography variant="h2" component="h1">
                MUI looks good
              </Typography>
              <Typography variant="p" component="p">
                You can perhaps see why this is a popular package.
              </Typography>
            </Box>
            <Box>
              <CustomizedTimeline></CustomizedTimeline>
            </Box>
          </Container>
        </main>
      </div>
    </>
  );
}
